deployments:
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzYwYWEzZjg2LTk3YTAtNDY4YS05OTQzLTIzNjZmMjFkOTk0Yy8yZjUzMjEzNC0wZmFkLTExZWMtOTFkYS0wZTNlN2EyMWE5MTE=
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzYwYWEzZjg2LTk3YTAtNDY4YS05OTQzLTIzNjZmMjFkOTk0Yy83NjYxYWNiZS05YmE2LTExZWMtYTBjMy0wZTNlN2EyMWE5MTE=
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzYwYWEzZjg2LTk3YTAtNDY4YS05OTQzLTIzNjZmMjFkOTk0Yy8yNjAyZjUxMC1hMDU3LTExZWMtYWIxYS0wZTNlN2EyMWE5MTE=
