deployments:
  services:
    ids:
    - asdad
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzYwYWEzZjg2LTk3YTAtaDY4Yas5OTQzLTIzNjZmMjFkOTk0Yy8yZjUzMjEzNC0wZmFkLTExZWMtOTFkYS0wZTNlN2EyMWE5MTE=
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzYwYWEzZjg2LTk3YTAtNDY4YS05OTQzLTIzNjZmMjFkOTk0Yy8yZjUzMjEzNC0wZmFkLTExZWMtOTFkYS0wZTNlN2EyMWE5MTE=
